spring:
  name: Elm AI

vector-db:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  database: ${DB_NAME:postgres}
  user: ${DB_USER:user-dev}
  password: ${DB_PASSWORD:password}

elm-ai:
  hugging-face-api-key: ${HF_API_KEY}
  openai-api-key: ${HF_API_KEY}
