pgvector:
  host: localhost
  port: 5432
  database: postgres
  user: ${DB_USER:user-dev}
  password: ${DB_PASSWORD:password}

elm-ai:
  hugging-face-api-key: ${HF_API_KEY}
  openai-api-key: ${HF_API_KEY}
