apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector-pvc
  namespace: elm-ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-sc
  resources:
    requests:
      storage: 500Mi