apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector
  namespace: elm-ai
  labels:
    app: pgvector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      containers:
        - name: pgvector
          image: ankane/pgvector:v0.5.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: elm
            - name: POSTGRES_USER
              value: elm
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgvector-secret
                  key: password
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgvector-pvc
